### ISSUE TITLE
System.MissingMethodException with New Umbraco Project -> v7.0.0 in VS 2013

### ISSUE THREAD

**Issue by jeroldhaas** [warrenbuckley/Umbraco-VS-New-Project#6]
__Visual Studio__: v2013
__Umbraco File New Project__: v1.3.0.0

After selecting v7.0.0 as Umbraco version at the WPF dialog:

    System.MissingMethodException: Error: Missing method 'instance void [Umbraco.VS.NewProject.Wizard.WPF] NuGet.VisualStudio.IVsPackageInstaller::InstallPackage(class [NuGet.Core]NuGet.IPackageRepository,class EnvDTE.Project,string,string,bool,bool)' from class 'NuGet.VisualStudio.VsPackageInstaller'.

    at NuGet.VisualStudio.IVsPackageInstaller.InstallPackage(IPackageRepository repository, Project project, String packageId, String version, Boolean ignoreDependencies, Boolean skipAssemblyReferences)

    at Umbraco.VS.NewProject.Wizard.WPF.Wizard.GetUmbraco(Project project, String umbracoNugetVersion)

    at Umbraco.VS.NewProject.Wizard.WPF.Wizard.ProjectFinishedGenerating(Project project)

**Comment by warrenbuckley** [comment]
Hi @jeroldhaas 
I am not entirely sure what this issue is with this at the moment.

I will need to investigate more. Seems like this issue has cropped up for other users as well and I have tried to get to the bottom of this before:

https://nuget.codeplex.com/discussions/471690
https://visualstudiogallery.msdn.microsoft.com/e8893648-f2f1-47cf-909c-53fff87a679a

I am not sure if I personally know how to combat & resolve this currently.
Can you get me as much diagnostic info about your machine/setup please, any VisualStudio extensions and what versions they are.

If you goto Visual Studio --> Help --> About and list out the extensions and their versions please.

**Comment by jeroldhaas** [comment]
@warrenbuckley Happy to help:

Windows 8.1 - VS details below:

---

``
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.53349

Installed Version: Ultimate

Architecture and Modeling Tools   06181-004-0451047-02662
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Team Explorer for Visual Studio 2013   06181-004-0451047-02662
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06181-004-0451047-02662
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0451047-02662
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0451047-02662
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0451047-02662
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06181-004-0451047-02662
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06181-004-0451047-02662
Windows Phone SDK 8.0 - ENU

AngularToolbox   1.0
Information about my package

ASP.NET and Web Tools   12.4.51016.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Websites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

CodeCop   1.0
CodeCop visualizes diagnostics messages

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Devart LINQ Insight Express   3.2.610.0
Devart LINQ Insight Express
Copyright © Devart 2012-2014. All rights reserved.
Web: www.devart.com/linqinsight
Support: support@devart.com

Elucidate   1.0
Alternative reading mode for F# that renders markdown interspersed in code.

JScriptStubOptions   1.0
Provides a way to make customizeable options for the JScript vsdoc Stub Generator.

Markdown mode for Visual Studio   1.0
Markdown mode for Visual Studio

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

MySQL for Visual Studio   1.1.4
Data design and management tools for MySQL.  Copyright © 2007-2014 Oracle, Inc.

NuGet Package Manager   2.8.50926.663
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PowerShell Tools for Visual Studio   1.0
Information about my package

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Data Tools   12.0.41025.0
Microsoft SQL Server Data Tools

Switch   1.0
Switch is an extension for Visual Studio that lets you quickly switch  between related files, such as cpp/h or code-behind and designer.

Visual F# Power Tools   1.7.0
Visual F# Power Tools

Visual Studio Tools for Unity   1.9.8.0
Visual Studio Tools for Unity

VS10x CodeMAP Package   1.1
Powerful Visual Studio code editor visualizer (C#, VB, C++).

VS10x Method Block Highlighter Package   1.2
Highlight entire methods with a colored background (green, yellow, cyan, magenta)

VSColorOutput   1.4.5
Color output for build and debug windows - http://blueonionsoftware.com/vscoloroutput.aspx

VsVim   1.7.1.1
VsVim is a Vim emulator for Visual Studio

Web Essentials 2013   2.5.3
Adds many useful features to Visual Studio for web developers.

Windows Azure Tools   2.3
Windows Azure Tools for Microsoft Visual Studio 2013 - v2.3.20320.1602

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Xamarin   3.9.236.0 (d6a2cae)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   4.20.0.34 (49a04b966feb40dfdba49d57ba16249b66d606a6)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.6.0.0 (eb24bdcf5cba2c12b673a07e0a8cce368b9563b3)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

``

**Comment by shaundodimead** [comment]
I managed to work around the issue by using a different method in nuget libs to achieve what was being done, I've forked and updated but submitted pull request. Hopefully someone can turn that into something useful for others!
